ta: stm32mp_cryp: fix compilation error on aarch64 architecture
Fixes a compilation error on aarch64 caused by using %d with size_t, which is
long unsigned int on that architecture.

ta/stm32mp_cryp/ta_stm32mp_cryp.c:351:22: error: format ‘%d’ expects argument of type ‘int’,
but argument 6 has type ‘size_t’ {aka ‘long unsigned int’} [-Werror=format=]
  351 |                 EMSG("Bad sizes: in %d, out %d", params[0].memref.size,
      |                      ^~~~~~~~~~~~~~~~~~~~~~~~~~  ~~~~~~~~~~~~~~~~~~~~~
      |                                     |
      |                                     size_t {aka long unsigned int}

https://onedigi.atlassian.net/browse/DEL-9634

Signed-off-by: Arturo Buzarra <arturo.buzarra@digi.com>